//! The stylesheets and fonts.
//!
//! The CSS comes in three parts, each a constant here, each wrapped in a
//! [cascade layer](https://developer.mozilla.org/en-US/docs/Web/CSS/@layer)
//! so that any unlayered rule in the host wins over it, whatever its
//! specificity:
//!
//! - [`STRUCTURE`], in the layer `rich-chat.structure`: what the
//!   components need to work. The containers that scroll and grow, the
//!   block wrappers that must not become boxes, and the alignment of
//!   MathML environments. No colors, fonts, spacing, or radii. Keep it.
//! - [`THEME`], in `rich-chat.theme`: the default look. Every color is
//!   a `--rc-*` custom property set on the outermost component root
//!   (`.rc-chat`, or a `.rc-rich` or `.rc-composer` used alone), so a
//!   host can override any of them there from its own stylesheet; or
//!   leave the whole theme out and write one against the `rc-*` classes.
//! - [`HIGHLIGHT`], also in `rich-chat.theme`: the code colors, from
//!   two-face's OneHalfLight and OneHalfDark. Generated, not written:
//!   `examples/highlight_css.rs` prints one theme's rules scoped to one
//!   side of the light and dark switch, and `assets/highlight.css` is
//!   two runs of it. Run it for any other two-face theme to swap the
//!   colors.
//!
//! None of it names anyone. Where each name's bubbles sit and what
//! colors they have is the host's [`Names`](crate::Names) table, whose
//! [`css`](crate::Names::css) is a fourth part in the same form, in
//! `rich-chat.theme`. The theme gives it `--rc-tail`, the radius of a
//! bubble's tail, and the plain bubble's `--rc-bubble-*` colors plus a
//! second pair, `--rc-tint-*`, which the default table uses for `user`
//! and the composer's preview takes. The name written over a bubble,
//! `.rc-sender`, is the theme's: small, in `--rc-muted`, whatever the
//! bubble's colors.
//!
//! [`STYLESHEET`] is all three. The [`RichChatStyle`](crate::RichChatStyle)
//! component injects them, each part switchable, or a consumer can serve
//! them as files.
//!
//! The layering cuts both ways. Every unlayered rule in the host wins,
//! including the ones it did not aim at the chat: a global reset that
//! flattens headings or strips button backgrounds (Tailwind 3's
//! preflight is one) applies inside the bubbles too, and the host
//! restores what it wants by rule against the `rc-*` classes. A host
//! whose own rules are in layers is subject to the order the layers are
//! first declared in, and [`RichChatStyle`](crate::RichChatStyle) puts
//! the crate's CSS in a `<style>` element in the body, after anything in
//! the document's head: declare the order yourself, first, to put yours
//! after them:
//!
//! ```css
//! @layer rich-chat.structure, rich-chat.theme, base, components, utilities;
//! ```
//!
//! Dark mode in the theme follows `prefers-color-scheme` unless the
//! document sets `data-theme="light"` or `data-theme="dark"` on its root
//! element, in which case that wins.
//!
//! Equations are set in Latin Modern Math, the TeX font, so they look the
//! same everywhere. With the `bundled-fonts` feature (the default) the
//! fonts are embedded and [`font_faces`] returns `@font-face` rules that
//! carry them as data URIs; without it, [`font_faces_from`] builds the
//! same rules for fonts served from a directory, and [`FONT_FILES`] has
//! the bytes to serve.

/// The rules the components need to work, in the layer
/// `rich-chat.structure`. See the [module docs](self).
pub const STRUCTURE: &str = concat!(
    "@layer rich-chat.structure, rich-chat.theme;\n",
    "@layer rich-chat.structure {\n",
    include_str!("../assets/structure.css"),
    "}\n",
);

/// The default look, in the layer `rich-chat.theme`: palette, fonts,
/// spacing, radii, and the light and dark switch.
pub const THEME: &str = concat!(
    "@layer rich-chat.structure, rich-chat.theme;\n",
    "@layer rich-chat.theme {\n",
    include_str!("../assets/theme.css"),
    "}\n",
);

/// The code highlighting colors, in the layer `rich-chat.theme`.
/// Generated by `examples/highlight_css.rs`; regenerate rather than edit.
pub const HIGHLIGHT: &str = concat!(
    "@layer rich-chat.structure, rich-chat.theme;\n",
    "@layer rich-chat.theme {\n",
    include_str!("../assets/highlight.css"),
    "}\n",
);

/// All three parts: [`STRUCTURE`], [`THEME`], and [`HIGHLIGHT`].
pub const STYLESHEET: &str = concat!(
    "@layer rich-chat.structure, rich-chat.theme;\n",
    "@layer rich-chat.structure {\n",
    include_str!("../assets/structure.css"),
    "}\n",
    "@layer rich-chat.theme {\n",
    include_str!("../assets/theme.css"),
    "\n",
    include_str!("../assets/highlight.css"),
    "}\n",
);

/// The math fonts by file name, for a consumer that serves them itself.
/// Latin Modern, under the GUST Font License.
pub const FONT_FILES: [(&str, &[u8]); 4] = [
    (
        "latinmodern-math.woff2",
        include_bytes!("../assets/fonts/latinmodern-math.woff2"),
    ),
    (
        "lmroman12-regular.woff2",
        include_bytes!("../assets/fonts/lmroman12-regular.woff2"),
    ),
    (
        "lmroman12-bold.woff2",
        include_bytes!("../assets/fonts/lmroman12-bold.woff2"),
    ),
    (
        "lmroman12-italic.woff2",
        include_bytes!("../assets/fonts/lmroman12-italic.woff2"),
    ),
];

/// `@font-face` rules that load the math fonts from `base_url`, a
/// directory URL with or without a trailing slash.
pub fn font_faces_from(base_url: &str) -> String {
    let base = base_url.trim_end_matches('/');
    font_face_rules(|file| format!("{base}/{file}"))
}

/// `@font-face` rules with the fonts embedded as data URIs. Built once,
/// on first use. Empty without the `bundled-fonts` feature.
pub fn font_faces() -> &'static str {
    #[cfg(feature = "bundled-fonts")]
    {
        static RULES: std::sync::LazyLock<String> = std::sync::LazyLock::new(|| {
            font_face_rules(|file| {
                let bytes = FONT_FILES
                    .iter()
                    .find(|(name, _)| *name == file)
                    .map(|(_, bytes)| *bytes)
                    .unwrap_or_default();
                format!("data:font/woff2;base64,{}", base64(bytes))
            })
        });
        &RULES
    }
    #[cfg(not(feature = "bundled-fonts"))]
    {
        ""
    }
}

fn font_face_rules(url: impl Fn(&str) -> String) -> String {
    let faces = [
        (
            "Latin Modern Math",
            "latinmodern-math.woff2",
            "normal",
            "normal",
        ),
        (
            "Latin Modern Roman",
            "lmroman12-regular.woff2",
            "normal",
            "normal",
        ),
        (
            "Latin Modern Roman",
            "lmroman12-bold.woff2",
            "bold",
            "normal",
        ),
        (
            "Latin Modern Roman",
            "lmroman12-italic.woff2",
            "normal",
            "italic",
        ),
    ];
    let mut css = String::new();
    for (family, file, weight, style) in faces {
        css.push_str(&format!(
            "@font-face{{font-family:\"{family}\";font-weight:{weight};font-style:{style};\
             font-display:swap;src:local(\"{family}\"),url(\"{}\") format(\"woff2\");}}\n",
            url(file)
        ));
    }
    css
}

#[cfg(feature = "bundled-fonts")]
fn base64(bytes: &[u8]) -> String {
    const TABLE: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = String::with_capacity(bytes.len().div_ceil(3) * 4);
    for chunk in bytes.chunks(3) {
        let n = chunk
            .iter()
            .enumerate()
            .fold(0u32, |acc, (i, &b)| acc | (u32::from(b) << (16 - 8 * i)));
        for i in 0..4 {
            if i <= chunk.len() {
                out.push(TABLE[((n >> (18 - 6 * i)) & 63) as usize] as char);
            } else {
                out.push('=');
            }
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[cfg(feature = "bundled-fonts")]
    #[test]
    fn base64_matches_the_standard() {
        assert_eq!(base64(b""), "");
        assert_eq!(base64(b"f"), "Zg==");
        assert_eq!(base64(b"fo"), "Zm8=");
        assert_eq!(base64(b"foo"), "Zm9v");
        assert_eq!(base64(b"foobar"), "Zm9vYmFy");
        assert_eq!(base64(&[0xff, 0xfe, 0xfd]), "//79");
    }

    #[cfg(feature = "bundled-fonts")]
    #[test]
    fn embedded_font_faces_cover_every_font() {
        let css = font_faces();
        assert_eq!(css.matches("@font-face").count(), 4);
        assert_eq!(css.matches("data:font/woff2;base64,").count(), 4);
        assert!(css.contains("\"Latin Modern Math\""));
    }

    #[test]
    fn served_font_faces_point_at_the_directory() {
        let css = font_faces_from("/fonts/");
        assert!(
            css.contains("url(\"/fonts/latinmodern-math.woff2\")"),
            "{css}"
        );
        assert_eq!(css.matches("@font-face").count(), 4);
    }

    #[test]
    fn the_stylesheet_has_all_three_parts() {
        assert!(STYLESHEET.contains(".rc-chat"));
        assert!(STYLESHEET.contains(".rc-rich math"));
        assert!(STYLESHEET.contains(".rc-keyword"));
        assert_eq!(
            STYLESHEET.matches("@layer rich-chat.structure {").count(),
            1
        );
        assert_eq!(STYLESHEET.matches("@layer rich-chat.theme {").count(), 1);
    }

    #[test]
    fn each_part_declares_the_layer_order_and_its_own_layer() {
        for (part, layer) in [
            (STRUCTURE, "structure"),
            (THEME, "theme"),
            (HIGHLIGHT, "theme"),
        ] {
            assert!(
                part.starts_with("@layer rich-chat.structure, rich-chat.theme;\n"),
                "{layer} part does not declare the layer order"
            );
            assert!(
                part.contains(&format!("@layer rich-chat.{layer} {{")),
                "{layer} part is not in its layer"
            );
            assert!(part.trim_end().ends_with('}'), "{layer} part is not closed");
        }
    }

    #[test]
    fn the_structure_has_no_colors_and_the_theme_has_the_palette() {
        for line in STRUCTURE.lines() {
            assert!(
                !line.contains("var(--rc-"),
                "structure uses a theme variable: {line}"
            );
            assert!(!line.contains('#'), "structure has a color: {line}");
        }
        assert!(THEME.contains("--rc-accent:"));
        assert!(STRUCTURE.contains(".rc-block {"));
        assert!(STRUCTURE.contains("mtable.menv-alignlike"));
    }

    #[test]
    fn the_stylesheet_names_no_one() {
        for word in [
            "[data-name=",
            "[data-kind=",
            "rc-message-",
            "rc-user",
            "rc-assistant",
            "rc-system",
        ] {
            assert!(
                !STYLESHEET.contains(word),
                "the stylesheet knows a name: {word}"
            );
        }
        assert!(THEME.contains("--rc-tail:"));
        assert!(THEME.contains("--rc-bubble-bg:"));
        assert!(THEME.contains("--rc-tint-bg:"));
        assert!(
            THEME.contains(".rc-sender {"),
            "the name over a bubble is themed"
        );
        assert!(
            STRUCTURE.contains(
                ".rc-message {\n  display: flex;\n  flex-direction: column;\n  align-items: flex-start;"
            ),
            "a message is a column the names rules align"
        );
    }
}
