//! The stylesheets and fonts.
//!
//! The CSS comes in three parts, each a constant here, each wrapped in a
//! [cascade layer](https://developer.mozilla.org/en-US/docs/Web/CSS/@layer)
//! so that any unlayered rule in the host wins over it, whatever its
//! specificity:
//!
//! - [`STRUCTURE`], in the layer `rich-chat.structure`: what the
//!   components need to work. The containers that scroll and grow, the
//!   block wrappers that must not become boxes, and the alignment of
//!   MathML environments. No colors, fonts, spacing, or radii. Keep it.
//! - [`THEME`], in `rich-chat.theme`: the default look. Every color is
//!   a `--rc-*` custom property declared on the document root, so a host
//!   can override any of them from its own stylesheet, on `.rc-chat` or
//!   on any other ancestor of the components; or leave the whole theme
//!   out and write one against the `rc-*` classes.
//! - [`HIGHLIGHT`], also in `rich-chat.theme`: the code colors, from
//!   two-face's OneHalfLight and OneHalfDark. Generated, not written:
//!   `examples/highlight_css.rs` prints one theme's rules scoped to one
//!   side of the light and dark switch, and `assets/highlight.css` is
//!   two runs of it. Run it for any other two-face theme to swap the
//!   colors. Its classes are the highlighter's `hl-*`, never the
//!   components' `rc-*`, so a rule against either cannot land on the
//!   other; a test here holds the two sets apart.
//!
//! None of it names anyone. Where each name's bubbles sit and what
//! colors they have is the host's [`Names`](crate::Names) table, whose
//! [`css`](crate::Names::css) is a fourth part in the same form, in
//! `rich-chat.theme`. The theme gives it `--rc-tail`, the radius of a
//! bubble's tail, and the plain bubble's `--rc-bubble-*` colors plus a
//! second pair, `--rc-tint-*`, which the default table uses for `user`
//! and the composer's preview takes. The name written over a bubble,
//! `.rc-sender`, is the theme's: small, in `--rc-muted`, whatever the
//! bubble's colors. So is the widest a bubble gets,
//! `--rc-bubble-max-width`, `min(85%, 76ch)` by default: one value for
//! the whole chat rather than a name's, which `.rc-bubble` reads, so a
//! host's own body that takes that class gets the maximum with the
//! padding and the background. The crate does not clamp it: a host that
//! sets `20ch` gets `20ch`.
//!
//! [`STYLESHEET`] is all three. The [`RichChatStyle`](crate::RichChatStyle)
//! component injects them, each part switchable, or a consumer can serve
//! them as files.
//!
//! The layering cuts both ways. Every unlayered rule in the host wins,
//! including the ones it did not aim at the chat: a global reset that
//! flattens headings or strips button backgrounds (Tailwind 3's
//! preflight is one) applies inside the bubbles too, and the host
//! restores what it wants by rule against the `rc-*` classes. A host
//! whose own rules are in layers is subject to the order the layers are
//! first declared in, and [`RichChatStyle`](crate::RichChatStyle) puts
//! the crate's CSS in a `<style>` element in the body, after anything in
//! the document's head: declare the order yourself, first, with the
//! crate's layers after any layer that resets elements and before any
//! layer whose rules should win over the theme, as the README's
//! [Styling section](https://github.com/wpm/Rich-Chat/tree/main/leptos-rich-chat#styling)
//! explains. For Tailwind v4, whose preflight is in `base`:
//!
//! ```css
//! @layer theme, base, rich-chat, components, utilities;
//! @import "tailwindcss";
//! ```
//!
//! Dark mode in the theme follows `prefers-color-scheme` unless the
//! document sets `data-theme="light"` or `data-theme="dark"` on its root
//! element, in which case that wins.
//!
//! Equations are set in Latin Modern Math, the TeX font, so they look the
//! same everywhere. With the `bundled-fonts` feature (the default) the
//! fonts are embedded and [`font_faces`] returns `@font-face` rules that
//! carry them as data URIs; without it, [`font_faces_from`] builds the
//! same rules for fonts served from a directory, and [`FONT_FILES`] has
//! the bytes to serve.

/// The rules the components need to work, in the layer
/// `rich-chat.structure`. See the [module docs](self).
pub const STRUCTURE: &str = concat!(
    "@layer rich-chat.structure, rich-chat.theme;\n",
    "@layer rich-chat.structure {\n",
    include_str!("../assets/structure.css"),
    "}\n",
);

/// The default look, in the layer `rich-chat.theme`: palette, fonts,
/// spacing, radii, and the light and dark switch.
pub const THEME: &str = concat!(
    "@layer rich-chat.structure, rich-chat.theme;\n",
    "@layer rich-chat.theme {\n",
    include_str!("../assets/theme.css"),
    "}\n",
);

/// The code highlighting colors, in the layer `rich-chat.theme`.
/// Generated by `examples/highlight_css.rs`; regenerate rather than edit.
pub const HIGHLIGHT: &str = concat!(
    "@layer rich-chat.structure, rich-chat.theme;\n",
    "@layer rich-chat.theme {\n",
    include_str!("../assets/highlight.css"),
    "}\n",
);

/// All three parts: [`STRUCTURE`], [`THEME`], and [`HIGHLIGHT`].
pub const STYLESHEET: &str = concat!(
    "@layer rich-chat.structure, rich-chat.theme;\n",
    "@layer rich-chat.structure {\n",
    include_str!("../assets/structure.css"),
    "}\n",
    "@layer rich-chat.theme {\n",
    include_str!("../assets/theme.css"),
    "\n",
    include_str!("../assets/highlight.css"),
    "}\n",
);

/// The math fonts by file name, for a consumer that serves them itself.
/// Latin Modern, under the GUST Font License.
pub const FONT_FILES: [(&str, &[u8]); 4] = [
    (
        "latinmodern-math.woff2",
        include_bytes!("../assets/fonts/latinmodern-math.woff2"),
    ),
    (
        "lmroman12-regular.woff2",
        include_bytes!("../assets/fonts/lmroman12-regular.woff2"),
    ),
    (
        "lmroman12-bold.woff2",
        include_bytes!("../assets/fonts/lmroman12-bold.woff2"),
    ),
    (
        "lmroman12-italic.woff2",
        include_bytes!("../assets/fonts/lmroman12-italic.woff2"),
    ),
];

/// `@font-face` rules that load the math fonts from `base_url`, a
/// directory URL with or without a trailing slash.
pub fn font_faces_from(base_url: &str) -> String {
    let base = base_url.trim_end_matches('/');
    font_face_rules(|file| format!("{base}/{file}"))
}

/// `@font-face` rules with the fonts embedded as data URIs. Built once,
/// on first use. Empty without the `bundled-fonts` feature.
pub fn font_faces() -> &'static str {
    #[cfg(feature = "bundled-fonts")]
    {
        static RULES: std::sync::LazyLock<String> = std::sync::LazyLock::new(|| {
            font_face_rules(|file| {
                let bytes = FONT_FILES
                    .iter()
                    .find(|(name, _)| *name == file)
                    .map(|(_, bytes)| *bytes)
                    .unwrap_or_default();
                format!("data:font/woff2;base64,{}", base64(bytes))
            })
        });
        &RULES
    }
    #[cfg(not(feature = "bundled-fonts"))]
    {
        ""
    }
}

fn font_face_rules(url: impl Fn(&str) -> String) -> String {
    let faces = [
        (
            "Latin Modern Math",
            "latinmodern-math.woff2",
            "normal",
            "normal",
        ),
        (
            "Latin Modern Roman",
            "lmroman12-regular.woff2",
            "normal",
            "normal",
        ),
        (
            "Latin Modern Roman",
            "lmroman12-bold.woff2",
            "bold",
            "normal",
        ),
        (
            "Latin Modern Roman",
            "lmroman12-italic.woff2",
            "normal",
            "italic",
        ),
    ];
    let mut css = String::new();
    for (family, file, weight, style) in faces {
        css.push_str(&format!(
            "@font-face{{font-family:\"{family}\";font-weight:{weight};font-style:{style};\
             font-display:swap;src:local(\"{family}\"),url(\"{}\") format(\"woff2\");}}\n",
            url(file)
        ));
    }
    css
}

#[cfg(feature = "bundled-fonts")]
fn base64(bytes: &[u8]) -> String {
    const TABLE: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = String::with_capacity(bytes.len().div_ceil(3) * 4);
    for chunk in bytes.chunks(3) {
        let n = chunk
            .iter()
            .enumerate()
            .fold(0u32, |acc, (i, &b)| acc | (u32::from(b) << (16 - 8 * i)));
        for i in 0..4 {
            if i <= chunk.len() {
                out.push(TABLE[((n >> (18 - 6 * i)) & 63) as usize] as char);
            } else {
                out.push('=');
            }
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeSet;

    use super::*;

    #[cfg(feature = "bundled-fonts")]
    #[test]
    fn base64_matches_the_standard() {
        assert_eq!(base64(b""), "");
        assert_eq!(base64(b"f"), "Zg==");
        assert_eq!(base64(b"fo"), "Zm8=");
        assert_eq!(base64(b"foo"), "Zm9v");
        assert_eq!(base64(b"foobar"), "Zm9vYmFy");
        assert_eq!(base64(&[0xff, 0xfe, 0xfd]), "//79");
    }

    #[cfg(feature = "bundled-fonts")]
    #[test]
    fn embedded_font_faces_cover_every_font() {
        let css = font_faces();
        assert_eq!(css.matches("@font-face").count(), 4);
        assert_eq!(css.matches("data:font/woff2;base64,").count(), 4);
        assert!(css.contains("\"Latin Modern Math\""));
    }

    #[test]
    fn served_font_faces_point_at_the_directory() {
        let css = font_faces_from("/fonts/");
        assert!(
            css.contains("url(\"/fonts/latinmodern-math.woff2\")"),
            "{css}"
        );
        assert_eq!(css.matches("@font-face").count(), 4);
    }

    #[test]
    fn the_stylesheet_has_all_three_parts() {
        assert!(STYLESHEET.contains(".rc-chat"));
        assert!(STYLESHEET.contains(".rc-rich math"));
        assert!(STYLESHEET.contains(".hl-keyword"));
        assert_eq!(
            STYLESHEET.matches("@layer rich-chat.structure {").count(),
            1
        );
        assert_eq!(STYLESHEET.matches("@layer rich-chat.theme {").count(), 1);
    }

    #[test]
    fn each_part_declares_the_layer_order_and_its_own_layer() {
        for (part, layer) in [
            (STRUCTURE, "structure"),
            (THEME, "theme"),
            (HIGHLIGHT, "theme"),
        ] {
            assert!(
                part.starts_with("@layer rich-chat.structure, rich-chat.theme;\n"),
                "{layer} part does not declare the layer order"
            );
            assert!(
                part.contains(&format!("@layer rich-chat.{layer} {{")),
                "{layer} part is not in its layer"
            );
            assert!(part.trim_end().ends_with('}'), "{layer} part is not closed");
        }
    }

    #[test]
    fn the_structure_has_no_colors_and_the_theme_has_the_palette() {
        for line in STRUCTURE.lines() {
            assert!(
                !line.contains("var(--rc-"),
                "structure uses a theme variable: {line}"
            );
            assert!(!line.contains('#'), "structure has a color: {line}");
        }
        assert!(THEME.contains("--rc-accent:"));
        assert!(STRUCTURE.contains(".rc-block {"));
        assert!(STRUCTURE.contains("mtable.menv-alignlike"));
    }

    /// The classes a stylesheet's selectors name: every `.name` outside
    /// a comment or a `@layer` line (whose dots are in the layer names),
    /// whether the crate's own or one of pulldown-cmark's and
    /// pulldown-latex's that the crate styles.
    fn classes_in(css: &str) -> BTreeSet<String> {
        let mut rest = css;
        let mut code = String::new();
        while let Some(start) = rest.find("/*") {
            code.push_str(&rest[..start]);
            let end = rest[start..]
                .find("*/")
                .map_or(rest.len(), |end| start + end + 2);
            rest = &rest[end..];
        }
        code.push_str(rest);
        let code: String = code
            .lines()
            .filter(|line| !line.trim_start().starts_with("@layer"))
            .collect::<Vec<_>>()
            .join("\n");
        let mut classes = BTreeSet::new();
        for candidate in code.split('.').skip(1) {
            let name: String = candidate
                .chars()
                .take_while(|c| c.is_ascii_alphanumeric() || matches!(c, '-' | '_'))
                .collect();
            // A number's decimal point is not a class.
            if name.starts_with(|c: char| c.is_ascii_alphabetic() || matches!(c, '-' | '_')) {
                classes.insert(name);
            }
        }
        classes
    }

    /// Every `rc-` word in the components' source: a superset of the
    /// classes they set on their elements.
    fn component_class_words() -> BTreeSet<String> {
        let source = concat!(
            include_str!("components.rs"),
            include_str!("render/mod.rs"),
            include_str!("names.rs"),
        );
        source
            .match_indices("rc-")
            .map(|(at, _)| {
                source[at..]
                    .chars()
                    .take_while(|c| c.is_ascii_alphanumeric() || matches!(c, '-' | '_'))
                    .collect::<String>()
            })
            .filter(|word| word.len() > "rc-".len())
            .collect()
    }

    /// The highlighter's classes are its own. Every dotted atom of a
    /// TextMate scope becomes a class, so `meta.block` would be
    /// `rc-block` under the components' prefix and take the wrapper's
    /// rules, and `entity.name.function` would be `rc-name`, so a rule
    /// of the theme's for a class of that name would recolor every
    /// function name. No class the components, the structure and theme
    /// stylesheets, or the names' rules use may be a class in the
    /// highlight stylesheet.
    #[test]
    fn the_highlight_classes_are_nobody_elses() {
        let prefix = crate::render::code::CLASS_PREFIX;
        let highlight = classes_in(HIGHLIGHT);
        assert!(highlight.contains("hl-keyword"), "{highlight:?}");
        assert!(
            highlight.iter().all(|class| class.starts_with(prefix)),
            "a highlight class without the {prefix} prefix: {highlight:?}"
        );

        let mut used = classes_in(STRUCTURE);
        used.extend(classes_in(THEME));
        used.extend(classes_in(&crate::Names::default().css()));
        used.extend(component_class_words());
        for class in [
            "rc-block",
            "rc-sender",
            "rc-code",
            "rc-copied",
            "menv-alignlike",
        ] {
            assert!(
                used.contains(class),
                "{class} is not among the classes in use"
            );
        }

        let collisions: Vec<_> = highlight.intersection(&used).collect();
        assert!(
            collisions.is_empty(),
            "highlight classes that the components or the stylesheets also use: {collisions:?}"
        );
    }

    #[test]
    fn the_stylesheet_names_no_one() {
        for word in [
            "[data-name=",
            "[data-kind=",
            "rc-message-",
            "rc-user",
            "rc-assistant",
            "rc-system",
        ] {
            assert!(
                !STYLESHEET.contains(word),
                "the stylesheet knows a name: {word}"
            );
        }
        assert!(THEME.contains("--rc-tail:"));
        assert!(THEME.contains("--rc-bubble-bg:"));
        assert!(THEME.contains("--rc-tint-bg:"));
        assert!(
            THEME.contains(".rc-sender {"),
            "the name over a bubble is themed"
        );
        assert!(
            STRUCTURE.contains(
                ".rc-message {\n  display: flex;\n  flex-direction: column;\n  align-items: flex-start;"
            ),
            "a message is a column the names rules align"
        );
    }

    /// The widest a bubble gets is a token of the theme's, declared on
    /// the root with the rest so that a host takes it over from any
    /// ancestor, and read by the bubble's rule, so that a host's own body
    /// with the bubble's class gets it too. The default is the one value
    /// that was in the rule before it was a token.
    #[test]
    fn the_theme_declares_the_bubbles_maximum_width_and_the_bubble_reads_it() {
        assert!(
            THEME.contains("  --rc-bubble-max-width: min(85%, 76ch);\n"),
            "the theme declares the token with today's value as its default"
        );
        assert!(
            THEME.contains(".rc-bubble {\n  max-width: var(--rc-bubble-max-width);\n"),
            "the bubble reads the token"
        );
        assert_eq!(
            THEME.matches("--rc-bubble-max-width:").count(),
            1,
            "declared once, on the root, so an override anywhere above the chat wins"
        );
        assert!(
            !STRUCTURE.contains(".rc-bubble {\n  max-width")
                && !STRUCTURE.contains("--rc-bubble-max-width"),
            "the width is the theme's to give, not the structure's"
        );
    }

    /// A host's reset takes whatever list markers the theme leaves to the
    /// browser: layer order only arbitrates declarations both sides make.
    #[test]
    fn the_theme_declares_its_list_markers() {
        for rule in [
            ".rc-rich ul {\n  list-style-type: disc;\n}",
            ".rc-rich ol {\n  list-style-type: decimal;\n}",
            ".rc-rich :is(ul, ol) ul {\n  list-style-type: circle;\n}",
            ".rc-rich :is(ul, ol) :is(ul, ol) ul {\n  list-style-type: square;\n}",
            // On the item too, so that a reset of `li` itself, which would
            // beat a marker that only reaches the item by inheritance,
            // loses to the theme as one of `ul` and `ol` does.
            ".rc-rich li {\n  list-style-type: inherit;\n}",
        ] {
            assert!(THEME.contains(rule), "the theme lacks: {rule}");
        }
        // Both shapes of a task item: the checkbox is the item's first
        // child in a tight list, and its first paragraph's in a loose one.
        assert!(
            THEME.contains(
                ".rc-rich li:has(> input[type=\"checkbox\"], > p:first-child > input[type=\"checkbox\"]) {\n  list-style: none;"
            ),
            "a task-list item, tight or loose, has no marker"
        );
        assert!(
            THEME.contains(
                ".rc-rich li > input[type=\"checkbox\"],\n.rc-rich li > p:first-child > input[type=\"checkbox\"] {"
            ),
            "a task-list checkbox, tight or loose, is styled"
        );
    }
}
